fix(P02): add step for permission verification
Taro-IT/docs pull request #138
Opened 2021-10-28 21:44 UTC by eacp

Se añadió un paso para verificar que los documentos ligados al tablero SCAMPI tengan permisos para ver.

2021-11-01 23:31 UTC, JuanManuelAmador requested changes
Todo eso se podria agregar en una sola Checklist y ademas especificar quienes lo hacen

2021-11-01 23:31 UTC, JuanManuelAmador commented on docs/procesos/P09-proceso-entrega-de-scampi.md
> +
Para que puedan que?

2021-11-04 16:45 UTC, eacp commented on docs/procesos/P09-proceso-entrega-de-scampi.md
> +
Se han atendido los cambios y el PR se encuentra en espera de review

2021-11-05 18:27 UTC, A01208320 approved these changes

2021-11-06 01:39 UTC, karlaromerox3 approved these changes

2021-11-06 01:44 UTC, merged