docs: :memo: create code review process
Taro-IT/docs pull request #142
Opened 2021-11-02 01:37 UTC by Maualvm

2021-11-02 01:55 UTC, JoseCarlosPa submitted a review, later dismissed

2021-11-03 02:38 UTC, EricBL3 requested changes

2021-11-03 02:38 UTC, EricBL3 commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>Si un ítem no se cumple, se registra en el Defect Log y se corrige.</li>
Esto está repetido en la última oración del punto pasado.

2021-11-03 02:38 UTC, EricBL3 commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>Si no se encontraron defectos, la pareja aprueba el PR, notifica al autor, y se hace el merge a dev y borra la rama en la que se trabajaron los cambios.</li>
```suggestion
          <li>Si no se encontraron defectos, la pareja aprueba el PR, notifica al autor, se hace el merge a dev y se borra la rama en la que se trabajaron los cambios.</li>
```

2021-11-03 02:38 UTC, EricBL3 commented on docs/procesos/P31-proceso-revision-codigo.md
> +
Meter lo de la bitácora de cambios.

2021-11-03 02:38 UTC, EricBL3 commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>La pareja que revisa el PR se dirige a la sección Files Changed para ver los archivos que fueron modificados en este PR.</li>
Aquí se podría ligar la guía de revisión de assets especificando que sería útil para algo departamental o de documentación y no de código de los proyectos.

2021-11-03 21:32 UTC, EricBL3 approved these changes

2021-11-03 21:36 UTC, merged