Feat/p30 proceso toma decisiones
Taro-IT/docs pull request #143
Opened 2021-11-02 05:40 UTC by RGalaviz

2021-11-03 14:36 UTC, JanLimpensG commented on docs/procesos/P02-proceso-juntas-socios-formadores.md
> +| 1. Planeación    | <ul align="left"><li>Se deberán definir, en equipo y previo a la junta, los temas a tratar con su respectiva duración, teniendo en cuenta que se deberá dejar tiempo para:</li><ul
¿Por qué se hicieron estos cambios?

2021-11-10 03:08 UTC, JoseCarlosPa submitted a review, later dismissed

2021-11-11 15:29 UTC, karlaromerox3 requested changes
Pls resuelve los conflictos

2021-11-12 02:31 UTC, IvanDiazPeralta submitted a review, later dismissed
LGTM

2021-11-12 03:24 UTC, RGalaviz commented on docs/procesos/P02-proceso-juntas-socios-formadores.md
> +| 1. Planeación    | <ul align="left"><li>Se deberán definir, en equipo y previo a la junta, los temas a tratar con su respectiva duración, teniendo en cuenta que se deberá dejar tiempo para:</li><ul
Porque daba que hay un <li> volando

2021-11-12 03:24 UTC, RGalaviz commented on docs/procesos/P02-proceso-juntas-socios-formadores.md
> +| 1. Planeación    | <ul align="left"><li>Se deberán definir, en equipo y previo a la junta, los temas a tratar con su respectiva duración, teniendo en cuenta que se deberá dejar tiempo para:</li><ul
un bullet point volando *** te odio markdown

2021-11-12 04:32 UTC, AAcostac requested changes

2021-11-12 04:32 UTC, AAcostac commented on docs/procesos/P30-proceso-toma-de-decisiones.md
> +          <li>Tomar la decisión.</li>
Creo que este paso deberia ir en la etapa de desicion, bajo "Si la decisión es pertinente"

2021-11-12 16:25 UTC, RGalaviz commented on docs/procesos/P30-proceso-toma-de-decisiones.md
> +          <li>Tomar la decisión.</li>
Si, tienes razón, ya lo cambié

2021-11-12 16:30 UTC, JuanManuelAmador requested changes
checa que el package-lock no genere errores en las pruebas de docosaurus

2021-11-12 17:08 UTC, AAcostac submitted a review, later dismissed

2021-11-12 17:19 UTC, AAcostac approved these changes

2021-11-12 17:21 UTC, merged