docs: medidas de prevencion a POL03
Taro-IT/docs pull request #149
Opened 2021-11-08 18:47 UTC by A01208320

Se agregaron las medidas de prevención y la de acción para la protección de los datos.

2021-11-11 03:42 UTC, RGalaviz requested changes

2021-11-11 03:42 UTC, RGalaviz commented on docs/codigo-etica.md
> -- Raúl Rosario Sandoval Galaviz
se murieron los autores?

2021-11-12 01:03 UTC, angieanaya commented on docs/politicas/POL03-politica-manejo-datos.md
>  ### Respaldo de Información
Quitar letra mayúscula a "Información"

2021-11-12 01:09 UTC, angieanaya requested changes
Estás cambiando el proceso de retro de SCAMPI pero creo que rompes el formato, revisa eso y mis demás comentarios,

2021-11-12 01:09 UTC, angieanaya commented on docs/politicas/POL03-politica-manejo-datos.md
> +- Las [lineas base](https://taro-it.github.io/docs/politicas/POL04-Definicion%20de%20elementos%20de%20configuracion) de los proyectos deberán ser clonados por todos los miembros de Taro, se deberá re
Líneas, días y miércoles llevan acento. Cambiar lo de "mantener actualizadas las líneas base." por "para mantenerlas actualizadas".

2021-11-12 01:09 UTC, angieanaya commented on docs/politicas/POL03-politica-manejo-datos.md
> +
agregó lleva acento

2021-11-12 02:14 UTC, AAcostac commented on docs/codigo-etica.md
> -- Raúl Rosario Sandoval Galaviz
Debe ser un error al jalar los cambios de `main`

2021-11-12 02:34 UTC, AAcostac commented on docs/politicas/POL03-politica-manejo-datos.md
> +- Las [lineas base](https://taro-it.github.io/docs/politicas/POL04-Definicion%20de%20elementos%20de%20configuracion) de los proyectos deberán ser clonados por todos los miembros de Taro, se deberá re
Conciso, buena idea.

2021-11-12 04:02 UTC, AAcostac approved these changes

2021-11-12 17:49 UTC, IvanDiazPeralta approved these changes
LGTM

2021-11-12 18:02 UTC, merged