Docs/p 31/refactor process
Taro-IT/docs pull request #153
Opened 2021-11-08 23:45 UTC by eacp

Para el PPQA

2021-11-12 17:03 UTC, JoseCarlosPa approved these changes

2021-11-12 17:35 UTC, JuanManuelAmador requested changes
A la espera del refactor del proceso que creo angie para combinar ambos, no hagan el PR hasta que este aprobado por ella y este listo este refactor

2021-11-13 02:03 UTC, angieanaya commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>Abrir la <a href="../checklists/CH02-checklist-items-trabajo">checklist de items de trabajo</a> correspondiente al equipo y al tipo de item (hacer una copia local si es necesario), y ve
Desde esta fase se debe duplicar la checklist para que el owner marque si lo que realizó cumple con la checklist, esta será la checklist que deberá de abrir el verificador posteriormente. 
(según la checklist que crearon los del equipo de ppqa)

2021-11-13 02:04 UTC, angieanaya commented on docs/procesos/P31-proceso-revision-codigo.md
> +                <li>Si el item es código, *** registrar el incumplimiento en el Defect Log usando la [guía  para el Defect Log](https://taro-it.github.io/docs/guias/G17-guia-defect-log).</li>
se fueron unos símbolos (***) de más.

2021-11-13 02:05 UTC, angieanaya commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>Si el item es código, completar el PR haciendo el merge a dev y borrando la rama en la que se trabajaron los cambios.</li>
esto ya se especifica en la guia para realizar un pull request, estaría bien linkearla.

2021-11-13 02:07 UTC, angieanaya commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>Comunicar en la junta diaria del equipo o a través del canal de slack taro-medio-camino o taro-cinica según corresponda, que el artefacto ha sido creado/modificado y está listo para su
sería mejor poner item de trabajo en lugar de artefacto para ser consistentes.

2021-11-13 02:08 UTC, angieanaya requested changes
Ahora la verificación por parte del owner tambien se registra dentro de las checklists por eso el duplicar la hoja desde la fase de preparación del dueño es importante.

2021-11-16 02:54 UTC, AAcostac approved these changes

2021-11-16 02:54 UTC, AAcostac commented on docs/procesos/P31-proceso-revision-codigo.md
> +            <li>Si es un artefacto de análisis o diseño, a la carpeta correspondiente</li>
¿Deberiamos indicar exactamente donde se guardan estos?

2021-11-16 02:54 UTC, AAcostac commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>En la sección correspondiente al tipo del item, llenar los campos: ID, nombre del item de trabajo, versión y verificador. La version debe seguir el formato [ID_PRODUCTODETRABAJO]-VER[00
¿Deberiamos aclarar que se hace si no es la primera verificacion de alguna fase para el item? Por ejemplo, si se hace una verificacion de codigo y se encuentran errores, se corrigen y luego se hace otra verificacion, ¿que pasa con la primera? se sobreescribe? ¿o pegas una copia de la checklist al lado?

2021-11-16 13:56 UTC, angieanaya commented on docs/procesos/P31-proceso-revision-codigo.md
> +          <li>En la sección correspondiente al tipo del item, llenar los campos: ID, nombre del item de trabajo, versión y verificador. La version debe seguir el formato [ID_PRODUCTODETRABAJO]-VER[00
versión lleva acento

2021-11-16 23:32 UTC, EricBL3 commented on docs/procesos/P31-proceso-revision-codigo.md
> +            <li>Si es un artefacto de análisis o diseño, a la carpeta correspondiente</li>
creo que ahí ya depende de como lo maneje cada equipo

2021-11-16 23:35 UTC, EricBL3 commented on docs/procesos/P31-proceso-revision-codigo.md
> +            <li>Si es un artefacto de análisis o diseño, a la carpeta correspondiente</li>
Esto no depende de la manera específica de trabajar de cada equipo? En frappé por ejemplo lo subiamos al confluence y ponemos un ss en el manual de arquitectura del caso.

2021-11-17 00:44 UTC, AAcostac approved these changes

2021-11-17 15:43 UTC, JoseCarlosPa approved these changes

2021-11-17 15:44 UTC, merged