Pp/add wows
Taro-IT/docs pull request #157
Opened 2021-11-09 03:59 UTC by dinnos

Definición de WOWs en la wiki PP 

@Taro-IT/espresso podrían revisar si su WOW esta actualizado, gracias.

2021-11-11 03:47 UTC, RGalaviz requested changes

2021-11-11 03:47 UTC, RGalaviz commented on docs/forma-de-trabajo/forma-de-trabajo-taro.md
> +![Mapa de Procesos](../../static/img/mapa-procesos-2.PNG)
Este mapa no es el actualizado, poner nueva imagen.

2021-11-12 16:51 UTC, JuanManuelAmador requested changes

2021-11-12 16:51 UTC, JuanManuelAmador commented on docs/forma-de-trabajo/forma-de-trabajo-espresso.md
> +- Architecture Owner: [Juan Manuel Amador Pérez Flores](mailto:a01701248@itesm.mx)
aqui podriamos crear un excel donde traiga el historico y mejor apunta desde aqui hacia ese excel, yo por ejemplo ahorita soy team leader no AO

2021-11-16 03:07 UTC, AAcostac commented on docs/forma-de-trabajo/forma-de-trabajo-espresso.md
> +- Architecture Owner: [Juan Manuel Amador Pérez Flores](mailto:a01701248@itesm.mx)
tenemos [uno incompleto](https://docs.google.com/spreadsheets/d/138hOit4VKnIF8iJlYP9AAkDv1ZDCaNug5S_VPua2ICQ/edit#gid=1300370628) de espresso

2021-11-16 06:25 UTC, eacp approved these changes
Ahora que ya están los cambios lo veo bien.

2021-11-23 23:12 UTC, EricBL3 approved these changes

2021-11-23 23:13 UTC, merged