docs: Modificar procesos para que incluyan obtencion y análisis de me…
Taro-IT/docs pull request #177
Opened 2021-11-12 13:41 UTC by sebastafoya

Modificar procesos para que incluyan obtención y análisis de metricas

2021-11-13 16:23 UTC, JanLimpensG requested changes

2021-11-13 16:23 UTC, JanLimpensG commented on docs/procesos/P20-proceso-retrospective.md
> +          <li>Se toman decisiones para mejorar los resultados en la siguiente iteración después de analizar las métricas.</li>
Hace falta poner el link del proceso 30 (el de toma de decisiones)

2021-11-16 00:03 UTC, AAcostac commented on docs/procesos/P20-proceso-retrospective.md
> +          <li>Se toman decisiones para mejorar los resultados en la siguiente iteración después de analizar las métricas.</li>
El paso de toma de desiciones despues del analisis se va a mover al proceso de analisis de metricas

2021-11-16 00:06 UTC, AAcostac approved these changes
El enlace al proceso de analisis se agregara en cuanto se apruebe el PR de ese.

2021-11-16 00:10 UTC, JanLimpensG approved these changes

2021-11-16 00:11 UTC, merged