Refactor P06 a P32
Taro-IT/docs pull request #180
Opened 2021-11-12 18:26 UTC by JJDiazAndre

Cambios en el proceso a partir de retro de Lalo.

2021-11-13 02:45 UTC, angieanaya requested changes

2021-11-13 02:45 UTC, angieanaya commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 1. Verificación | <ul><li>Verificar la integridad de los datos obtenidos según los criterios de análisis definido.</li><li>En caso de que los datos salgan de los márgenes de los criterios de anális
Falta una "s" en "criterios de análisis definido." ¿Cómo se desactiva una métrica? supongo que es quitando el check en la casilla de la columna "Activa" pero se debe de especificar en el proceso.

2021-11-13 02:45 UTC, angieanaya commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 2. Análisis | <ul><li>Analizar los datos obtenidos.</li><li>Tomar decisiones a partir del análisis.</li></ul>| <ul><li>M&A - 2.2</li></ul> |
Se debería de enlazar al proceso de toma de decisiones.

2021-11-13 02:45 UTC, angieanaya commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 3. Comunicación | <ul><li>Comunicar las decisiones tomadas y plasmarlas en las herramientas pertinentes a la métrica analizada.</li></ul>| <ul><li>M&A - 2.3</li><li>M&A - 2.4</li></ul> |
¿Por dondé se comunicaría la decisión tomada? slack, daily meeting departamental o de equipo

2021-11-13 02:45 UTC, angieanaya commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 2. Análisis | <ul><li>Analizar los datos obtenidos.</li><li>Tomar decisiones a partir del análisis.</li></ul>| <ul><li>M&A - 2.2</li></ul> |
Esto de analizar los datos obtenidos, es solo en caso de que la verificación anterior haya sido exitosa, no? o incluso si los datos obtenidos no son integros, se analizan?

2021-11-13 02:45 UTC, angieanaya commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 3. Comunicación | <ul><li>Comunicar las decisiones tomadas y plasmarlas en las herramientas pertinentes a la métrica analizada.</li></ul>| <ul><li>M&A - 2.3</li><li>M&A - 2.4</li></ul> |
¿A quién se le comunica la decisión tomada?

2021-11-13 02:45 UTC, angieanaya commented on docs/procesos/P32-proceso-analisis-metricas.md
> +- [Historial de experimentos](https://docs.google.com/spreadsheets/d/1SIO7qeEihTUOkOuSJZM-Lc6AryG9LPsFKonwZ_kYtCg/edit#gid=597584843).
¿En qué momento se llena este historial de experimentos dentro del proceso? o ¿Porque el historial de experimentos, las juntas con socios y departamentales serían una salida?

2021-11-16 00:52 UTC, AAcostac commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 1. Verificación | <ul><li>Verificar la integridad de los datos obtenidos según los criterios de análisis definido.</li><li>En caso de que los datos salgan de los márgenes de los criterios de anális
Ahora se especifica

2021-11-16 00:52 UTC, AAcostac commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 3. Comunicación | <ul><li>Comunicar las decisiones tomadas y plasmarlas en las herramientas pertinentes a la métrica analizada.</li></ul>| <ul><li>M&A - 2.3</li><li>M&A - 2.4</li></ul> |
Eso se va a mover a otro proceso

2021-11-16 00:54 UTC, AAcostac commented on docs/procesos/P32-proceso-analisis-metricas.md
> +- [Historial de experimentos](https://docs.google.com/spreadsheets/d/1SIO7qeEihTUOkOuSJZM-Lc6AryG9LPsFKonwZ_kYtCg/edit#gid=597584843).
La idea es que vienes a este proceso de otros a conseguir el analisis de las metricas que usan y que despues de ese analisis tomes una desicion o propongas una mejora a la forma de trabajo de ser necesario. Pero esta parte se va a mover a otro proceso.
Lo de los otros procesos era por la parte de la comunicacion que se va a quitar de aqui como puse arriba.

2021-11-16 01:06 UTC, AAcostac commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 2. Análisis | <ul><li>Analizar los datos obtenidos.</li><li>Tomar decisiones a partir del análisis.</li></ul>| <ul><li>M&A - 2.2</li></ul> |
Se agrego la aclaracion sobre cuando continuar despues de la verificacion.

2021-11-16 01:06 UTC, AAcostac commented on docs/procesos/P32-proceso-analisis-metricas.md
> +| 2. Análisis | <ul><li>Analizar los datos obtenidos.</li><li>Tomar decisiones a partir del análisis.</li></ul>| <ul><li>M&A - 2.2</li></ul> |
Tambien se conectara con el proceso de toma de desiciones en el mapa de procesos.

2021-11-16 01:17 UTC, AAcostac approved these changes

2021-11-16 06:30 UTC, eacp approved these changes
Gracias por corregir la ortografía.

2021-11-16 13:43 UTC, angieanaya approved these changes

2021-11-16 13:44 UTC, merged