Refactor de P06 a proceso de definicion de metricas
Taro-IT/docs pull request #181
Opened 2021-11-12 21:30 UTC by AAcostac

Se antendio la retroalimentacion  de Eduardo Juarez y se cambio el proceso de obtención y análisis de métricas a uno de definicion (este) y otro de [analisis](https://github.com/Taro-IT/docs/pull/180).

2021-11-13 02:16 UTC, angieanaya commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Especificar el objetivo que se quiere alcanzar y registrarlo en la columna de "Objetivo". Este debe de estar planteado de forma que especifica y medible.</li>
Este debe de estar planteado de forma que *sea* especifica y medible. Una pregunta, ¿No debería de ser smart el objetivo?

2021-11-13 02:17 UTC, angieanaya commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Identificar opciones de métricas para cubrir el objetivo planteado.</li>
¿Cómo se identifican estas opciones de métricas? ¿Habrá una guía o solo será en base al objetivo con lo que cada quién decida?

2021-11-13 02:19 UTC, angieanaya commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Verificar en la matriz de métricas que la métrica seleccionada no es redundante con las que se encuentran en uso. En caso de serlo, descartar la métrica.</li>
¿No estaría bien hacer esta verificación al principio cuando se define el objetivo para evitar hacer trabajo de más?

2021-11-13 02:20 UTC, angieanaya commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Especificar la periodicidad con la que se analizaran los datos obtenidos para la métrica en la columna de "Frecuencia de análisis".</li>
analizarán lleva acento

2021-11-13 02:50 UTC, angieanaya requested changes

2021-11-13 02:50 UTC, angieanaya commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Especificar el objetivo que se quiere alcanzar y registrarlo en la columna de "Objetivo". Este debe de estar planteado de forma que especifica y medible.</li>
¿ En qué momento marcas la casilla de "Activa"? ¿En qué momento se define la prioridad de la métrica y como se debe de hacer esa priorización? ¿En qué momento defines los interesados y como los indentificas?

2021-11-15 18:55 UTC, AAcostac commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Verificar en la matriz de métricas que la métrica seleccionada no es redundante con las que se encuentran en uso. En caso de serlo, descartar la métrica.</li>
Como el objetivo puede ser similar entre varias metricas, se hace la verificacion hasta que especificas exactamente que vas a medir.

2021-11-15 18:57 UTC, AAcostac commented on docs/procesos/P06-proceso-definicion-metricas.md
> +          <li>Identificar opciones de métricas para cubrir el objetivo planteado.</li>
Es con base a lo que cada quien decida

2021-11-16 06:35 UTC, eacp approved these changes
Ortografía corregida

2021-11-16 13:38 UTC, angieanaya approved these changes

2021-11-16 13:39 UTC, merged