docs: modificar G15 para realizar un plan de comunicación
Taro-IT/docs pull request #186
Opened 2021-11-15 16:36 UTC by A01208320

- Se modificó G15 para realizar un plan de comunicación con los interesados
- Se arreglaron errores de formato

2021-11-16 01:40 UTC, AAcostac requested changes

2021-11-16 01:40 UTC, AAcostac commented on docs/procesos/P14-proceso-de-definicion-del-plan-inicial.md
> +| 1. Identificación | <ul><li>Definir las fases del ciclo de vida del plan </li> <li>Ver qué recursos y habilidades se necesitan para el plan [(Usar la plantilla de vision statement)](../plantillas/P
Como puse en el PR de la politica de conocimiento, en los pasos de este proceso que tienen  que ver con planear el conocimieto no se deberian de usar los artefactos que se especifican alla?

2021-11-16 01:40 UTC, AAcostac commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +- Definir los horarios en las cuales es posible tener la comunicación.
Hay alguna plantilla para esto?

2021-11-16 01:40 UTC, AAcostac commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +- Identificar los 4 cuadrantes de la matriz de interesados:
```suggestion
Un interesado, también llamado Stakeholder, son personas o entidades que tienen algún tipo de interés en el proyecto y que pueden afectar o ser afectadas por este. Este paso involucra:

- Identificar a los interesados.
- Identificar los 4 cuadrantes de la matriz de interesados:
```

2021-11-16 06:29 UTC, eacp submitted a review, later dismissed

2021-11-17 01:28 UTC, angieanaya requested changes

2021-11-17 01:28 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +Un interesado, también llamado Stakeholder, son personas o entidades con quienes el proyecto tiene algún tipo de relación como puedan ser actividades y relaciones.
stakeholder debería de ser con s minúscula, no es un nombre propio

2021-11-17 01:28 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +- Identificar los 4 cuadrantes de la matriz de interesados:
¿A qué se refiere con identificar los 4 cuadrantes de la matriz a literal solo ver los cuadrantes? ¿O los cuadrantes cambian según se requiera?

2021-11-17 01:28 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +- Definir los horarios en las cuales es posible tener la comunicación.
```suggestion
- Definir los horarios en los cuales es posible comunicarse con los interesados.
```

2021-11-17 01:28 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +Por cada interesado hay que detallar todas las formas de comunicación que se tendrá, esto involucra:
¿En dónde se detalla esto? ¿en la misma matriz, dentro del plan? hay que especificar

2021-11-19 17:58 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
Utilizando la plantilla de del [plan de comunicación](https://docs.google.com/document/d/1xUNELhNh5GLmtP1Yc-Hpe1vKqYLWoW2B46EBego_jAA/edit#heading=h.7h46sxtb142z) se deberá de realizar y documentar lo siguiente:

2021-11-19 18:01 UTC, angieanaya requested changes

2021-11-19 18:01 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +- Usar símbolos o nombres para identificar a cada interesado dentro de esta matriz, por ejemplo:
Yo quitaría lo de simbolos.

2021-11-19 18:01 UTC, angieanaya commented on docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
> +Se puede usar la siguiente [plantilla](../plantillas/PL16-plantilla-para-plan-comunicacion).
Si se agrega en la parte inicial de la guía esta línea se debería de quitar.

2021-11-19 19:34 UTC, angieanaya approved these changes

2021-11-22 15:58 UTC, merged