feat(documentation): agregar proceso para juntas diarias P07
Taro-IT/docs pull request #43
Opened 2021-09-22 17:19 UTC by angieanaya

Se agrega el proceso de juntas diarias.

Closes #40

2021-09-22 17:27 UTC, JanLimpensG commented on docs/procesos/P07-proceso-juntas-diarias.md
> +| 3. Asignación de work items | Asignar work items a los integrantes del equipo que hayan completado con éxito los asignados en la junta de planeación y que tienen tiempo disponible según lo definido
Creo que en lugar de  "que tienen tiempo" sería mejor poner "que tengan tiempo", fuera de eso todo se ve bien

2021-09-22 18:24 UTC, EricBL3 requested changes
El contenido lo veo bien, solo hay que checar el comentario que puse y si se me olvidó decirles que ya cambió la parte de objetivos. Van a ir enlistados en vez de ponerlos como principal y secundario.

2021-09-22 18:24 UTC, EricBL3 commented on docs/procesos/P07-proceso-juntas-diarias.md
> +**Principal:**
```suggestion
```

2021-09-22 18:24 UTC, EricBL3 commented on docs/procesos/P07-proceso-juntas-diarias.md
> +Agilizar el proceso de desarrollo del equipo e identificar bloqueos en las actividades asignadas.
```suggestion
- Agilizar el proceso de desarrollo del equipo e identificar bloqueos en las actividades asignadas.
```

2021-09-22 18:24 UTC, EricBL3 commented on docs/procesos/P07-proceso-juntas-diarias.md
> +**Secundario:**
```suggestion
```

2021-09-22 18:24 UTC, EricBL3 commented on docs/procesos/P07-proceso-juntas-diarias.md
> +Informar sobre el estatus de todas las actividades *en progreso* a los integrantes del equipo.
```suggestion
- Informar sobre el estatus de todas las actividades *en progreso* a los integrantes del equipo.
```

2021-09-22 18:24 UTC, EricBL3 commented on docs/procesos/P07-proceso-juntas-diarias.md
> +| 1. Discusión de work items | Preguntar a cada integrante del equipo lo siguiente: <ul><li>¿En qué estuviste trabajando el día de ayer?</li><li>¿Tienes algún bloqueo para continuar con tus actividad
En las áreas involucradas falta poner cuál es el área porque ahorita solo está la práctica específica. Por ejemplo si es el caso, en vez de SP - 1.2, cambiarlo a PP - 1.2.

2021-09-23 17:28 UTC, EricBL3 approved these changes

2021-09-23 19:23 UTC, JoseCarlosPa approved these changes

2021-09-23 19:23 UTC, merged