feat: add wbs guide
Taro-IT/docs pull request #65
Opened 2021-09-24 16:45 UTC by karlaromerox3

2021-09-24 18:05 UTC, JoseCarlosPa submitted a review, later dismissed

2021-09-24 23:59 UTC, Maualvm requested changes
El archivo no es de tipo markdown, así que no se vería correctamente en la wiki (se vería como un txt tal cual), le puedes agregar la extensión .md para que se pueda subir porfa? @karlaromerox3

2021-09-25 03:00 UTC, Maualvm requested changes

2021-09-25 03:00 UTC, Maualvm commented on docs/guias/G07-guia-wbs.md
> +- [Plantilla para WBS](../plantillas/PL05-plantilla-para-wbs)
Falta corregir este link para que sea `../plantillas/PL05-plantilla-para-wbs.md` en lugar de `../plantillas/PL05-plantilla-para-wbs`

2021-09-25 05:49 UTC, Maualvm approved these changes

2021-09-25 20:10 UTC, merged