Fix/p14 proceso de definición de un plan
Taro-IT/docs pull request #71
Opened 2021-09-28 20:55 UTC by RGalaviz

closes #59 
Igual abre un nuevo issue, **crear un proceso de estimación de un work item.**

2021-09-28 23:47 UTC, EricBL3 requested changes
Veo todo bien. Solo hay que asegurarse de tener ya de una vez las prácticas específicas del CMMI en el proceso P06 que se les ocurra que pueden entrar. 

También acabo de ver que no debería ser el proceso P06, chequen los issues existentes y la guía de definición de assets para sacar el titulo. El P06 lo tiene el issue del proceso de métricas (que aún no existe pero el issue ya estaba).

2021-09-30 22:42 UTC, JuanManuelAmador approved these changes

2021-10-01 14:16 UTC, EricBL3 approved these changes
Veo bien todo a excepción del P06 pero para que eso no detenga los otros assets de este pr creo va a ser mejor hacer un task dentro del plan departamental para arreglarlo y que se hagan los cambios en otro pr.

2021-10-01 14:36 UTC, RGalaviz commented
> Veo bien todo a excepción del P06 pero para que eso no detenga los otros assets de este pr creo va a ser mejor hacer un task dentro del plan departamental para arreglarlo y que se hagan los cambios en otro pr.

El p06 solo le cambié la extensión de .mdx a .md, no deberia generar nada malo

2021-10-01 17:54 UTC, eacp approved these changes

2021-10-04 15:54 UTC, EricBL3 commented
> > Veo bien todo a excepción del P06 pero para que eso no detenga los otros assets de este pr creo va a ser mejor hacer un task dentro del plan departamental para arreglarlo y que se hagan los cambios en otro pr.
> 
> El p06 solo le cambié la extensión de .mdx a .md, no deberia generar nada malo

Me refiero mas bien a que ese proceso no está completo. Es el que Lalo dijo que no está con calidad de producción. Pero mejor que eso sea otro task y se arregle en otro pr. Yo diría que ya hagas merge de esto porque ya lleva casi una semana en review.

2021-10-04 15:56 UTC, JJDiazAndre approved these changes

2021-10-04 16:16 UTC, merged