Feat/g08 guia para el pm
Taro-IT/docs pull request #73
Opened 2021-09-29 17:09 UTC by JoseCarlosPa

feat: Addition of the PMs guide so any one can take de role

2021-09-30 17:54 UTC, AAcostac approved these changes

2021-09-30 17:54 UTC, AAcostac commented on docs/guias/G08-guia-para-el-pm.md
> +- Asegurarse de mantener el kanban board departamental ([Github](https://github.com/Taro-IT/docs/projects/1) o [Jira](https://taro-depto-ti.atlassian.net/jira/software/projects/TARO/boards/1)) actual
Si se deja de utilizar el GitHub así debería quitarse

2021-09-30 17:54 UTC, AAcostac commented on docs/guias/G08-guia-para-el-pm.md
> +### Habilidades a desarrollar
¿Esta parte de habilidades falta?

2021-09-30 21:00 UTC, EricBL3 commented on docs/guias/G08-guia-para-el-pm.md
> +### Habilidades a desarrollar
se nos fue quitar la sección

2021-09-30 21:30 UTC, JanLimpensG submitted a review, later dismissed

2021-09-30 22:39 UTC, JuanManuelAmador requested changes

2021-09-30 22:39 UTC, JuanManuelAmador commented on docs/guias/G08-guia-para-el-pm.md
> +
¿De que es el ultimo responsable el PM ?

2021-09-30 22:39 UTC, JuanManuelAmador commented on docs/guias/G08-guia-para-el-pm.md
> +- Animar y empoderar a los integrantes a poner en marcha las propuestas de mejora.
¿Como se realiza esta actividad de animar y empoderar ?

2021-09-30 22:39 UTC, JuanManuelAmador commented on docs/guias/G08-guia-para-el-pm.md
> +- Conocer el estado de cada uno de los proyectos.
¿que actividades hacen para conocer el estado de los proyectos ?

2021-09-30 22:39 UTC, JuanManuelAmador commented on docs/guias/G08-guia-para-el-pm.md
> +- Planeación departamental basándose en el pool de horas departamentales.
¿donde esta el pool de horas departamentales?

2021-09-30 23:23 UTC, EricBL3 commented on docs/guias/G08-guia-para-el-pm.md
> +
¿A qué te refieres con la pregunta? ¿Poner algo más directo de última responsabilidad además de las que están de la línea 20-26?

2021-10-01 17:54 UTC, eacp submitted a review, later dismissed

2021-10-04 21:22 UTC, EricBL3 commented on docs/guias/G08-guia-para-el-pm.md
> +- Animar y empoderar a los integrantes a poner en marcha las propuestas de mejora.
Por el momento esto depende de la persona pero con la propuesta de Saúl del path de la fuerza ya habría una guía para esto.

2021-10-04 21:31 UTC, JanLimpensG approved these changes

2021-10-04 21:46 UTC, A01208320 approved these changes

2021-10-05 01:16 UTC, JuanManuelAmador approved these changes

2021-10-05 16:09 UTC, merged